@baseUrl = http://localhost:5000/api

### 1. Obtener Lista de todos los Hoteles Activos
GET {{baseUrl}}/hotels

### 2. Buscar Hoteles por término (Nombre o Descripción)
GET {{baseUrl}}/hotels/search?query=Paradise

### 3. Obtener Detalle de un Hotel específico (Ejemplo: h1)
GET {{baseUrl}}/hotels/h1

### 4. Obtener las Comodidades (Amenities) del Hotel (Ejemplo: h1)
GET {{baseUrl}}/hotels/h1/amenities

### 5. Obtener Habitaciones disponibles del Hotel (Ejemplo: h1)
GET {{baseUrl}}/hotels/h1/rooms