### ==============================================================================
### VARIABLES GLOBALES DEL MÓDULO
### ==============================================================================
@baseUrl = http://localhost:5000/apis/v1
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc4Mjc0OTg1MiwianRpIjoiNmJhMDgyMjctNDI0Zi00YzUzLTgwNTUtM2VjM2Q2YTI0ZDAwIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InVzcl8xNzgyNzY3MjAyIiwibmJmIjoxNzgyNzQ5ODUyLCJjc3JmIjoiMjllNGUwNTktMzIwNC00NWY5LWI1YTMtMGRmZDcyMWQzZjhkIiwiZXhwIjoxNzgzMzU0NjUyfQ.zm_Zcq8mBt-_dzf2P-bd8NlaIYsA7LAh2poT-9Aw8YU

### Registrar un nuevo usuario
POST {{baseUrl}}/users/register
Content-Type: application/json

{
    "email": "carlos_flutter_4@example.com",
    "password": "mi_password_segura",
    "name": "Carlos",
    "lastname": "Mendoza",
    "phone": "+51999888777",
    "nationality": "Peruano",
    "stars_available": 100
}

###

### Iniciar sesión (Login)
POST {{baseUrl}}/users/login
Content-Type: application/json

{
    "email": "carlos_flutter_4@example.com",
    "password": "mi_password_segura"
}

###

### Validar vigencia del Token (Usado por interceptores de sesión en Flutter)
GET {{baseUrl}}/users/validate-token
Authorization: Bearer {{token}}

###

### Obtener mis datos de perfil completos
GET {{baseUrl}}/users/me
Authorization: Bearer {{token}}

###

### Actualizar datos del perfil (Cambiar a PUT)
PUT {{baseUrl}}/users/profile
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "lastname": "Mendoza Silva",
    "phone": "+51900111222"
}

###

### Recuperar Contraseña (Simulación de envío de correo)
POST {{baseUrl}}/users/forgot-password
Content-Type: application/json

{
    "email": "carlos_flutter@example.com"
}

###

### Cerrar sesión (Logout - Envía token actual a la lista negra)
POST {{baseUrl}}/users/logout
Authorization: Bearer {{token}}